<?php
$fields = array(
    array("name" => "data[title]", "data" => "Продам 2GB DDR2-800Mhz PC2-6400 CL6 ECC Unbuffered 240PIN DIMM"),
    array("name" => "data[category_id]", "data" => "458"),
    array("name" => "data[offer_seek]", "data" => ""),
    array("name" => "data[param_price][0]", "data" => "price"),
    array("name" => "data[param_price][1]", "data" => "30"),
    array("name" => "data[param_price][currency]", "data" => "USD"),
    array("name" => "data[param_subcategory]", "data" => "moduli-pamyati"),
    array("name" => "[param_currency]", "data" => ""),
    array("name" => "data[param_state]", "data" => "used"),
    array("name" => "data[private_business]", "data" => "private"),
    array("name" => "data[description]", "data" => "2GB DDR2-800Mhz PC2-6400 CL6 ECC Unbuffered 240PIN DIMM Server Memory \n новая, есть 4 планки \n Kingston"),
    array("name" => "data[riak_key]", "data" => ""),
    array("name" => "image[1]", "data" => "@" . dirname(__FILE__) . "/ddr2.jpg"),
    array("name" => "image[2]", "type" => "file", "data" => ""),
    array("name" => "image[3]", "type" => "file", "data" => ""),
    array("name" => "image[4]", "type" => "file", "data" => ""),
    array("name" => "image[5]", "type" => "file", "data" => ""),
    array("name" => "image[6]", "type" => "file", "data" => ""),
    array("name" => "image[7]", "type" => "file", "data" => ""),
    array("name" => "image[8]", "type" => "file", "data" => ""),
    array("name" => "data[gallery_html]", "data" => "1"),
    array("name" => "data[city_id]", "data" => "268"),
    array("name" => "data[city]", "data" => "Киев, Киевская область, Дарницкий"),
    array("name" => "data[district_id]", "data" => "3"),
    array("name" => "loc-option", "data" => "loc-opt-2"),
    array("name" => "data[map_zoom]", "data" => "11"),
    array("name" => "data[map_lat]", "data" => "50.40931"),
    array("name" => "data[map_lon]", "data" => "30.69263"),
    array("name" => "data[phone]", "data" => "+380674434935"),
    array("name" => "data[payment_code]", "data" => ""),
    array("name" => "data[sms_number]", "data" => ""),
    array("name" => "data[adding_key]", "data" => $addingKey),
    array("name" => "paidadFirstPrice", "data" => ""),
    array("name" => "paidadChangesLog", "data" => ""),
    array("name" => "data[suggested_categories][0]", "data" => "85"),
    array("name" => "data[suggested_categories][1]", "data" => "458"),
    array("name" => "data[suggested_categories][2]", "data" => "80"),
    array("name" => "data[suggested_categories][3]", "data" => "78"),
    array("name" => "data[map_radius]", "data" => "0"),
    array("name" => "data[suggested_category]", "data" => "458"),
);
